baseurl = "https://dave.xn--tckwe/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Show reading time in minutes for posts
  showReadingTime = false
  description = "dave's blog about his adventures on and off-line"
  images = ["/img/binary.webp"]

[social]
  twitter = "davebit_"
  linkedin = "davmontali"

[languages]
  [languages.en]
    title = "dave's site"
    keywords = "dave davide montali davebit"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "Monday, 2 Jan, 2006"
    dateFormatList = "Monday, 2 Jan, 2006"

    [languages.en.params.logo]
      logoText = "dave montali"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
